overrides:
  "@earendil-works/pi-ai": "$@earendil-works/pi-coding-agent"
  "@earendil-works/pi-tui": "$@earendil-works/pi-coding-agent"

allowBuilds:
  esbuild: true
  protobufjs: true
  "@google/genai": false

minimumReleaseAgeExclude:
  - '@aliou/pi-utils-settings@0.19.2'
  - '@earendil-works/chord@0.87.0'
  - '@earendil-works/pi-agent-core@0.87.0'
  - '@earendil-works/pi-ai@0.87.0'
  - '@earendil-works/pi-coding-agent@0.87.0'
  - '@earendil-works/pi-telemetry@0.87.0'
  - '@earendil-works/pi-tui@0.87.0'
